services:
  netcheck-exporter:
    build:
      context: ./netcheck-api
      dockerfile: Dockerfile
    container_name: netcheck-exporter
    environment:
      - PING_ADDRESS=8.8.8.8
      # - SPEEDTEST_PORT=<speedtest-port> #optional, but recomended against
      # - SPEEDTEST_SERVER=<server-id> #optional, but recomended against
    ports:
      - 9798:9798
    restart: unless-stopped

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - '9090:9090' # Expose Prometheus on port 9090
    volumes:
      - /prometheus
    env_file:
      - .env
    restart: unless-stopped
networks:
  default:
    driver: bridge # Ensure both services are on the same network
