{
 "title": "Speedtest-Exporter Dashboard",
 "description": "Dashboard for Speedtest Exporter https://github.com/MiguelNdeCarvalho/speedtest-exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(speedtest_up, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(speedtest_up, job)"
    }
   },
   {
    "name": "device_name",
    "label": "Device Name",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   { "name": "threshold_bandwidth_warning", "label": "Bandwidth Warning", "query": "70" },
   { "name": "threshold_bandwidth_error", "label": "Bandwidth Error", "query": "50" }
  ]
 },
 "panels": [
  { "title": "Summary [All devices]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Ping",
   "type": "stat",
   "description": "The average ping of the last scrape",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "custom_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"} != -1",
     "legendFormat": "{{origin_prometheus}}"
    }
   ]
  },
  {
   "title": "Ping Timeline",
   "type": "state-timeline",
   "description": "Displays health of ping over time",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "repeat": "device_name",
   "targets": [
    {
     "expr": "custom_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"} != -1",
     "legendFormat": "{{origin_prometheus}}"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "stat",
   "description": "The download speed of the last scrape",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\"} != -1)*10^-6",
     "legendFormat": "{{origin_prometheus}}"
    }
   ]
  },
  {
   "title": "Success Status Timeline",
   "type": "state-timeline",
   "description": "Displays if and when the internet tests have failed (Pings can fail if enough pings timeout). Speed test values are cached as not to exceed rate limits from Ookla. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "ping_up{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Ping: {{origin_prometheus}}"
    },
    {
     "expr": "speedtest_up{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Speedtest: {{origin_prometheus}}"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "stat",
   "description": "The download speed of the last scrape",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\"} != -1)*10^-6",
     "legendFormat": "{{origin_prometheus}}"
    }
   ]
  },
  { "title": "Summary [Individual Device]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Success Status Timeline",
   "type": "state-timeline",
   "description": "Displays if and when the internet tests have failed. Speed test values are cached as not to exceed rate limits from Ookla. ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ping_up{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "speedtest_up{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success status of the Speedtest-Exporter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_up{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"}"
    }
   ]
  },
  {
   "title": "Last Speedtest",
   "type": "stat",
   "description": "When was the last successful speed test?",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(speedtest_up{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"}==1)*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ServerID (Last test done)",
   "type": "stat",
   "description": "ServerID of the last test done",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_server_id{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"} and speedtest_up{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"} == 1"
    }
   ]
  },
  {
   "title": "Success status of the Custom Ping",
   "type": "stat",
   "description": "Default ping is 8.8.8.8 (Google)",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_up{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"}"
    }
   ]
  },
  {
   "title": "Last Ping",
   "type": "stat",
   "description": "When was the last successful ping?",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(ping_up{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"}==1)*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ping and Packet loss", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Average Ping",
   "type": "gauge",
   "description": "The average ping of several pings in milliseconds (from last scrape)",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "custom_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"} != -1"
    }
   ]
  },
  {
   "title": "Ping and Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "custom_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"} != -1",
     "legendFormat": "Ping (ms)"
    },
    {
     "expr": "custom_packet_loss{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"} != -1",
     "legendFormat": "Packet Loss (%)"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "gauge",
   "description": "The packet loss estimate of several pings from last scrape",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "custom_packet_loss{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"} != -1"
    }
   ]
  },
  { "title": "Speed tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"} != -1)*10^-6"
    }
   ]
  },
  {
   "title": "Download Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "(speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"} != -1)*10^-6",
     "legendFormat": "Download Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Upload Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "(speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"}!=-1)*10^-6",
     "legendFormat": "Upload Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\", origin_prometheus=\"$device_name\"}!=-1)*10^-6"
    }
   ]
  },
  { "title": "Graphics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } }
 ]
}